/**
 * AI-assisted issue analysis and fix generation (rule-based, dynamic per issue).
 */

import { generateBuildFixSuggestion } from "./ciAnalysis.js";
import { buildLineDiff } from "./diffUtils.js";
import {
    analyzeFileContent,
    getFileTypeFromPath,
    repairHtmlStructure,
} from "./localFileAnalysis.js";
import { fetchRepoFileContent } from "./repoFileContent.js";

const SCAN_STEPS = [
    { id: "fetch", label: "Fetching affected file" },
    { id: "validate", label: "Validating file structure" },
    { id: "analyze", label: "Analyzing syntax and patterns" },
    { id: "rootcause", label: "Identifying root cause" },
    { id: "generate", label: "Generating proposed fix" },
];

export function getScanSteps() {
    return SCAN_STEPS;
}

function slugify(text) {
    return String(text || "issue")
        .toLowerCase()
        .replace(/[^a-z0-9]+/g, "-")
        .replace(/^-|-$/g, "")
        .slice(0, 36);
}

function buildCommitMessage(issue, filePath) {
    const fileName = filePath?.split("/").pop() || "file";
    const type = (issue.issueType || "issue").toLowerCase();

    if (type.includes("syntax")) return `Fix syntax error in ${fileName}`;
    if (type.includes("build")) return `Fix CI build failure in ${fileName}`;
    if (type.includes("security")) return `Resolve security issue in ${fileName}`;
    if (type.includes("complexity")) return `Refactor ${fileName} to reduce complexity`;
    if (issue.detail?.rule?.includes("html")) return `Repair broken HTML tag in ${fileName}`;
    if (issue.detail?.rule?.includes("js")) return `Resolve JavaScript error in ${fileName}`;
    if (issue.detail?.rule?.includes("css")) return `Fix CSS issue in ${fileName}`;
    return `Fix ${type} in ${fileName}`;
}

function buildPrContent(issue, filePath, rootCause) {
    const title = buildCommitMessage(issue, filePath);
    const body = [
        "## Summary",
        `City Hero AI detected and repaired an issue in \`${filePath}\`.`,
        "",
        "## Issue",
        `- **Type:** ${issue.issueType}`,
        `- **Severity:** ${issue.severity}`,
        "",
        "## Root Cause",
        rootCause,
        "",
        "## Affected File",
        `\`${filePath}\``,
        "",
        "## Fix",
        issue.suggestedFix || "Automated patch applied based on repository analysis.",
        "",
        "---",
        "*Generated by GitHub City Hero Challenge*",
    ].join("\n");

    return { title, body };
}

function inferRootCause(issue, analysisIssues, fileType) {
    if (issue.category === "fire" && issue.detail?.failedStep) {
        return `CI workflow "${issue.detail.workflowName}" failed at step "${issue.detail.failedStep}" on branch ${issue.detail.branch || "main"}.`;
    }

    const primary = analysisIssues[0] || issue.detail;
    if (primary?.title) return primary.title;
    if (primary?.rule === "html-unclosed") {
        const match = /Unclosed <(\w+)>/.exec(primary.title || "");
        return match
            ? `Missing closing tag for <${match[1]}> element.`
            : "Unclosed HTML element detected.";
    }
    if (primary?.rule === "html-close" || primary?.rule === "html-mismatch") {
        return "Malformed or mismatched HTML closing tag.";
    }
    if (primary?.rule === "html-attr") {
        return "Broken HTML attribute or unclosed quote in a tag.";
    }
    if (primary?.rule === "js-parse") {
        return `JavaScript syntax error${primary.line ? ` near line ${primary.line}` : ""}.`;
    }
    if (primary?.rule === "css-brace" || primary?.rule === "scss-brace") {
        return "Unbalanced CSS/SCSS braces — missing or extra closing brace.";
    }
    if (primary?.rule === "json-parse") {
        return "Invalid JSON structure — parse error in file content.";
    }
    if (issue.category === "security") {
        return issue.description || "Security vulnerability flagged by code scanning.";
    }
    if (issue.category === "complexity") {
        return `File complexity is elevated (${fileType || "source"} module needs refactoring).`;
    }
    return issue.description || "Issue detected during repository health scan.";
}

function tryFixBrokenClosingTags(content) {
    let fixed = content;
    let changed = false;

    const patterns = [
        [/<\/scri(?!pt>)/gi, "</script>"],
        [/<\/styl(?!e>)/gi, "</style>"],
        [/<\/div(?!>)/gi, "</div>"],
        [/<\/span(?!>)/gi, "</span>"],
        [/<\/a(?!>)/gi, "</a>"],
        [/<\/p(?!>)/gi, "</p>"],
        [/<\/body(?!>)/gi, "</body>"],
        [/<\/html(?!>)/gi, "</html>"],
    ];

    for (const [pattern, replacement] of patterns) {
        if (pattern.test(fixed)) {
            fixed = fixed.replace(pattern, replacement);
            changed = true;
        }
    }

    return { fixed, changed };
}

const HTML_ISSUE_RULE_PRIORITY = [
    "html-mismatch",
    "html-unclosed",
    "html-close",
    "html-attr",
    "html-dom",
];

function pickPrimarySyntaxIssue(issues = []) {
    if (!issues.length) return null;
    for (const rule of HTML_ISSUE_RULE_PRIORITY) {
        const hit = issues.find((issue) => issue.rule === rule);
        if (hit) return hit;
    }
    return issues[0];
}

export function normalizeFixContent(content) {
    return String(content ?? "").replace(/\r\n/g, "\n");
}

export function fixContentChanged(original, fixed) {
    return (
        normalizeFixContent(original) !== normalizeFixContent(fixed)
    );
}

function tryFixMissingBrace(content, fileType) {
    let open = 0;
    for (const ch of content) {
        if (ch === "{") open++;
        else if (ch === "}") open--;
    }
    if (open <= 0) return { fixed: content, changed: false };
    const suffix = "\n" + "}".repeat(open) + "\n";
    return { fixed: content.trimEnd() + suffix, changed: true };
}

function tryFixTrailingCommaJson(content) {
    const fixed = content.replace(/,(\s*[}\]])/g, "$1");
    if (fixed === content) return { fixed: content, changed: false };
    try {
        JSON.parse(fixed);
        return { fixed, changed: true };
    } catch {
        return { fixed: content, changed: false };
    }
}

function tryFixUndefinedVariable(content, issueTitle) {
    const match = /'?(\w+)'?\s+is not defined/i.exec(issueTitle || "");
    if (!match) return { fixed: content, changed: false };
    const name = match[1];
    if (content.includes(`const ${name}`) || content.includes(`let ${name}`)) {
        return { fixed: content, changed: false };
    }
    const declaration = `const ${name} = undefined; // TODO: define ${name}\n`;
    return { fixed: declaration + content, changed: true };
}

function generateFixedContent(
    original,
    issue,
    analysisIssues,
    fileType,
    filePath = "",
) {
    let content = original;
    let changed = false;
    let fixStrategy = null;
    const primary = pickPrimarySyntaxIssue(analysisIssues);

    const isHtml =
        fileType === "html" ||
        fileType === "htm" ||
        primary?.rule?.startsWith("html") ||
        /\.html?$/i.test(filePath);

    if (isHtml) {
        const tagFix = tryFixBrokenClosingTags(content);
        if (tagFix.changed) {
            content = tagFix.fixed;
            changed = true;
            fixStrategy = "broken-closing-tags";
        }

        const structural = repairHtmlStructure(content);
        if (structural.changed) {
            content = structural.content;
            changed = true;
            fixStrategy = `html-structure-repair (${structural.passes} pass${
                structural.passes === 1 ? "" : "es"
            })`;
        }
    }

    if (
        primary?.rule === "css-brace" ||
        primary?.rule === "scss-brace" ||
        fileType === "css" ||
        fileType === "stylesheet"
    ) {
        const braceFix = tryFixMissingBrace(content, fileType);
        if (braceFix.changed) {
            content = braceFix.fixed;
            changed = true;
        }
    }

    if (primary?.rule === "json-parse" || fileType === "json") {
        const jsonFix = tryFixTrailingCommaJson(content);
        if (jsonFix.changed) {
            content = jsonFix.fixed;
            changed = true;
        }
    }

    if (primary?.rule === "js-parse" || fileType === "javascript") {
        const varFix = tryFixUndefinedVariable(content, primary?.title || "");
        if (varFix.changed) {
            content = varFix.fixed;
            changed = true;
        }
    }

    if (!changed && issue.category === "fire" && issue.suggestedFix) {
        const comment = [
            "",
            "/*",
            ` * City Hero CI Fix Note`,
            ` * Workflow: ${issue.detail?.workflowName || "unknown"}`,
            ` * Failed step: ${issue.detail?.failedStep || "unknown"}`,
            ` * ${issue.suggestedFix}`,
            " */",
            "",
        ].join("\n");
        content = comment + content;
        changed = true;
    }

    if (!changed && (issue.category === "security" || issue.category === "complexity")) {
        const banner = [
            "/**",
            ` * @city-hero-issue ${issue.issueType} (${issue.severity})`,
            ` * ${issue.description || issue.title}`,
            ` * Recommended: ${issue.suggestedFix || "Review and refactor this module."}`,
            " */",
            "",
        ].join("\n");
        if (!content.startsWith("/**")) {
            content = banner + content;
            changed = true;
        }
    }

    const reanalysis = analyzeFileContent(filePath || issue.filePath, content);
    const remaining = reanalysis.issues?.length || 0;
    const improved = remaining < (analysisIssues?.length || 1);

    const contentChanged = fixContentChanged(original, content);

    return {
        content,
        changed: changed && contentChanged,
        improved,
        remainingIssues: remaining,
        fixStrategy,
        primaryRule: primary?.rule || null,
    };
}

/**
 * Run full AI scan + fix generation pipeline.
 * @param {{ owner: string, repo: string, defaultBranch: string }} repoContext
 * @param {object} issue
 * @param {object} meta
 * @param {(stepIndex: number) => void} onProgress
 */
export async function runAiScanAndFix(repoContext, issue, meta, onProgress) {
    const filePath = meta.filePath || meta.path || issue.filePath;
    const fileType = getFileTypeFromPath(filePath);

    onProgress?.(0);
    await delay(280);

    const fileData = await fetchRepoFileContent(
        repoContext.owner,
        repoContext.repo,
        filePath,
        repoContext.defaultBranch,
    );

    onProgress?.(1);
    await delay(320);

    const originalContent = fileData?.content ?? "";
    const fileSha = fileData?.sha ?? null;

    onProgress?.(2);
    await delay(300);

    const analysis = analyzeFileContent(filePath, originalContent);
    const analysisIssues = analysis.issues?.length
        ? analysis.issues
        : issue.detail
        ? [issue.detail]
        : [];

    onProgress?.(3);
    await delay(350);

    const rootCause = inferRootCause(issue, analysisIssues, fileType);
    const explanation =
        issue.suggestedFix ||
        generateBuildFixSuggestion(issue.detail) ||
        `Analysis found ${issue.issueType} in ${filePath}. ${rootCause}`;

    onProgress?.(4);
    await delay(400);

    const fixResult = originalContent
        ? generateFixedContent(
              originalContent,
              issue,
              analysisIssues,
              fileType,
              filePath,
          )
        : {
              content: "",
              changed: false,
              improved: false,
              remainingIssues: 0,
              fixStrategy: null,
          };

    if (import.meta.env?.DEV) {
        console.group("[GitHub City Fix] AI content generation");
        console.log("File:", filePath);
        console.log("Issues found:", analysisIssues.length);
        console.log(
            "Primary rule:",
            fixResult.primaryRule || analysisIssues[0]?.rule,
        );
        console.log("Strategy:", fixResult.fixStrategy || "none");
        console.log("Original length:", originalContent.length);
        console.log("Fixed length:", fixResult.content?.length);
        console.log("Content changed:", fixResult.changed);
        console.log("Remaining issues:", fixResult.remainingIssues);
        console.groupEnd();
    }

    const fixedContent = fixResult.content || originalContent;
    const diff = buildLineDiff(originalContent || "(empty file)", fixedContent);
    const commitMessage = buildCommitMessage(issue, filePath);
    const pr = buildPrContent(issue, filePath, rootCause);
    const branchName = `ai-fix/${slugify(issue.issueType)}-${slugify(
        filePath.split("/").pop(),
    )}-${Date.now().toString(36).slice(-4)}`;

    return {
        filePath,
        fileType,
        fileSha,
        originalContent,
        fixedContent,
        diff,
        issueType: issue.issueType,
        severity: issue.severity,
        rootCause,
        explanation,
        suggestedFix: fixResult.changed
            ? `Automated patch applied to resolve: ${rootCause}`
            : explanation,
        canAutoFix: fixResult.changed && fixResult.content !== originalContent,
        improved: fixResult.improved,
        remainingIssues: fixResult.remainingIssues,
        commitMessage,
        prTitle: pr.title,
        prDescription: pr.body,
        branchName,
        scanSummary: {
            fileValidated: Boolean(fileData),
            issuesFound: analysisIssues.length,
            fileSize: fileData?.size ?? 0,
        },
    };
}

function delay(ms) {
    return new Promise((resolve) => setTimeout(resolve, ms));
}
